[project]
name = "ex-basics-3"
version = "0.1.0"
description = "Example CLI app with Typer"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
ex-basics-3 = "ex_basics_3.cli:app"
